version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: sportflow-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: sportflow
      POSTGRES_DB: sportflow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/sql/create_schema.sql:/docker-entrypoint-initdb.d/1_create_schema.sql
      - ./db/sql/data.sql:/docker-entrypoint-initdb.d/2_data.sql

volumes:
  postgres-data: